# Generated by Django 5.0.2 on 2024-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_empresa_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='isisDeleted',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
