# Generated by Django 5.0.2 on 2024-07-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_empresa_isisdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='isisDeleted',
            new_name='isDeleted',
        ),
    ]
