# Generated by Django 5.0.2 on 2024-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_isisdeleted_empresa_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
