# Generated by Django 5.0.2 on 2024-11-27 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isDeleted', models.CharField(blank=True, default=0, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.TextField()),
                ('descripcion', models.TextField()),
                ('acciones', models.TextField(blank=True, null=True)),
                ('personas', models.TextField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('adicionales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='incidentes/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidente_archivos', to='helpdesk.incidente')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isDeleted', models.CharField(blank=True, default=0, max_length=1, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.categoria')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField()),
                ('descripcion', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('En espera', 'En espera'), ('Respondido', 'Respondido'), ('Resuelto', 'Resuelto')], default='Nuevo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.problema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensaje/')),
                ('isFromClient', models.CharField(blank=True, max_length=1, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ticket/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_archivos', to='helpdesk.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('isDeleted', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.prioridad')),
            ],
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipoIncidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipoincidente'),
        ),
    ]
