# Generated by Django 5.0.2 on 2024-07-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('isDeleted', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Insidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField()),
                ('puesto', models.TextField()),
                ('descripcion', models.TextField()),
                ('acciones', models.TextField(blank=True, null=True)),
                ('personas', models.TextField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('adicionales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipoInsidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipoinsidente')),
            ],
        ),
    ]
