# Generated by Django 5.0.2 on 2024-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_tipoinsidente_insidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='isDeleted',
            field=models.CharField(blank=True, default=0, max_length=1, null=True),
        ),
    ]
