# Generated by Django 5.0.2 on 2024-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_ticket_id_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
