# Generated by Django 5.0.2 on 2024-07-29 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_categoria_isdeleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insidente',
            new_name='Incidente',
        ),
        migrations.RenameModel(
            old_name='TipoInsidente',
            new_name='TipoIncidente',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='tipoInsidente',
            new_name='tipoIncidente',
        ),
    ]
