# Generated by Django 5.0.2 on 2024-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_archivoincidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_custom',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
