# Generated by Django 5.0.2 on 2024-09-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_ticket_id_custom'),
        ('users', '0005_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresas',
            field=models.ManyToManyField(related_name='categorias', to='users.empresa'),
        ),
        migrations.AddField(
            model_name='problema',
            name='empresas',
            field=models.ManyToManyField(related_name='problemas', to='users.empresa'),
        ),
    ]
